## 대화창 실습 : numpy의 ndarray 사용

In [0]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [0]:
a.shape

(3,)

In [0]:
a.ndim 

1

In [0]:
a.dtype

dtype('int64')

In [0]:
a.itemsize

8

In [0]:
a.size

3

## 대화창 실습 : numpy와 데이터 형

In [0]:
a = np.array([1, 2, 3], dtype='int32')

In [0]:
b = np.array([4, 5, 6], dtype='int64')

In [0]:
a.dtype

dtype('int32')

In [0]:
b.dtype

dtype('int64')

In [0]:
c = a + b
c.dtype

dtype('int64')

### 주의 : 배열을 생성할 때 주의할 점들

In [0]:
a = np.array([1, 'two', 3, 4], dtype=np.int32)
a

ValueError: ignored

In [0]:
a = np.array([1, 'two', 3, 4])
a

## 대화창 실습 : ndarray의 메소드

In [0]:
import numpy as np
a = np.array([1, 2, 3])
a.max()

In [0]:
a.min()

In [0]:
a.mean()

## 대화창 실습 : ndarray의 flatten() 메소드

In [0]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a.flatten()

array([1, 1, 2, 2, 3, 3])

## 대화창 실습 : ndarray의 append() 함수

In [0]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.append([a], b, axis = 0)  # [a]를 통해 2차원 배열로 만들어야 함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 대화창 실습 : numpy의 ndarray의 덧셈(shape이 같을 경우)

In [0]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

## 대화창 실습 : numpy의 ndarray의 덧셈(shape이 다를 경우)

In [0]:
a = np.array([1, 2])
b = np.array([4, 5, 6])
c = a + b

ValueError: ignored

## 대화창 실습 : numpy의 2차원 ndarray의 연산

In [0]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10,20], [30,40]])
a + b

array([[11, 22],
       [33, 44]])

In [0]:
a - b

In [0]:
a * b

In [0]:
a / b

## 대화창 실습 : 행렬 곱 함수 matmul() 실습

In [0]:
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [0]:
a @ b

array([[ 70, 100],
       [150, 220]])

In [0]:
a[0,0] * b[0,0] + a[0,1] * b[1,0]

70

In [0]:
a[0,0] * b[0,1] + a[0,1] * b[1,1]

100

In [0]:
a[1,0] * b[0,0] + a[1,1] * b[1,0]

150

In [0]:
a[1,0] * b[0,1] + a[1,1] * b[1,1]

220

## 대화창 실습 : 행렬 곱 함수 matmul() 실습

In [0]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [0, 1]]
np.matmul(a, b)

## 대화창 실습 : 2차원 ndarray의 덧셈, 뺄셈, 곱셈, 나눗셈, 제곱 연산

In [0]:
a = np.array([[1, 2], [3, 4]])
a + 1

In [0]:
a - 1

In [0]:
a * 100

In [0]:
a / 100

In [0]:
a ** 2

## 대화창 실습 : 초기값을 가지는 배열의 생성

In [0]:
np.zeros((2, 3))

In [0]:
np.ones((2, 3))

In [0]:
np.full((2, 3), 100)

In [0]:
np.eye(3)

In [0]:
np.random.random((2, 3))

## 대화창 실습 : arange() 함수를 이용한 배열 생성

In [0]:
np.arange(0, 10)

In [0]:
np.arange(0, 10, 2)

In [0]:
np.arange(0, 10, 3)

In [0]:
np.arange(0.0, 1.0, 0.2)

## 대화창 실습 : linspace() 함수를 이용한 배열 생성

In [0]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [0]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## 대화창 실습 : reshape()을 이용한 배열의 재구성

In [0]:
np.arange(0,10).reshape(2,5)

In [0]:
np.arange(0,10).reshape(5,2)

In [0]:
np.arange(0,10).reshape(3,3)

## 대화창 실습 : 다른 차원으로의 reshape() 실습

In [0]:
np.arange(0, 24).reshape(4, 3, 2)

## 대화창 실습 : transpose() 함수

In [0]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
np.transpose(a)

array([[0, 2, 4],
       [1, 3, 5]])

## 대화창 실습 : sum 함수와 axis에 따른 원소의 합

In [0]:
a = np.arange(0,6).reshape(3,2)
a

In [0]:
a.sum() # 행렬의 모든 원소의 합

15

In [0]:
a.sum(axis = 0) # 0축 방향(행 방향) 원소의 합

array([6, 9])

## 대화창 실습 : 1축 방향 원소의 합

In [0]:
a.sum(axis = 1) # 1축 방향(열 방향) 원소의 합

array([1, 5, 9])

## 대화창 실습 : 0축과 1축 방향 원소의 최솟값 최댓값

In [0]:
a.min(axis=0) # 0축 방향 원소의 최솟값

In [0]:
a.min(axis=1) # 1축 방향 원소의 최솟값

In [0]:
a.max(axis=0) # 0축 방향 원소의 최솟값

In [0]:
a.max(axis=1) # 1축 방향 원소의 최솟값

## 대화창 실습 : ndarray의 insert() 함수

In [0]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

In [0]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 4, axis = 0)

In [0]:
np.insert(a, 1, (4, 4), axis = 0)

In [0]:
np.insert(a, 1, 4, axis = 1)

## 대화창 실습 : 1차원 배열의 인덱싱하기

In [0]:
a = np.array([1, 2, 3])
print(a[0], a[1], a[2])

1 2 3


In [0]:
print(a[-1], a[-2], a[-3])

3 2 1


## 대화창 실습 : 1차원 배열에서 여러 개의 원소를 인덱싱하기

In [0]:
a = np.array([1, 2, 3, 4])
print(a[np.array([0, 1])])

[1 2]


In [0]:
print(a[np.array([0, 1, 2])])

[1 2 3]


In [0]:
print(a[np.array([0, 1, 3])])

[1 2 4]


In [0]:
print(a[np.array([1, 1, 1, 1])])

[2 2 2 2]


## 대화창 실습 : 리스트와 슬라이싱

In [0]:
aList = [10, 20, 30, 40, 50, 60, 70, 80]
aList[1:5]

[20, 30, 40, 50]

## 대화창 실습 : NumPy의 슬라이싱

In [0]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[1:5]     # 슬라이싱 구간 [시작:끝] 인덱스

array([20, 30, 40, 50])

In [0]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80])

In [0]:
a[:]        # 전체를 슬라이싱

array([10, 20, 30, 40, 50, 60, 70, 80])

In [0]:
a[::2]      # 양수 2의 스텝값

array([10, 30, 50, 70])

In [0]:
a[::-1]     # 음수 스텝값

array([80, 70, 60, 50, 40, 30, 20, 10])

## 대화창 실습 : 2차원 배열의 인덱스

In [0]:
a = np.arange(0, 6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
print(a[0, 0])

0


In [0]:
print(a[0, 1])

1


In [0]:
print(a[0, 2])

IndexError: ignored

## 대화창 실습 : 3차원 배열의 인덱스

In [0]:
a = np.arange(0, 24).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [0]:
print(a[1, 2, 1])

11


## 대화창 실습 : 3차원 배열의 인덱스와 concatenate() 함수

In [0]:
a = np.arange(0, 24).reshape(4, 3, 2)
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
a[0, 0]

array([0, 1])

In [0]:
a[0, 1]

array([2, 3])

In [0]:
a[0, 2]

array([4, 5])

In [0]:
np.concatenate((a[0, 0], a[0, 2]), axis=0)

array([0, 1, 4, 5])

# 2차원 배열의 슬라이싱

In [0]:
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
print(a[0])

[0 1 2]


In [0]:
print(a[0, :])

[0 1 2]


In [0]:
print(a[:, 0])

[0 3 6]


In [0]:
print(a[0, 0:2])

[0 1]


In [0]:
print(a[0, :2])

[0 1]


In [0]:
print(a[:2, :2])

[[0 1]
 [3 4]]


In [0]:
print(a[1:, 1:])

[[4 5]
 [7 8]]


In [0]:
print(a[1, 1:])

[4 5]


In [0]:
print(a[1:2, 1:])

[[4 5]]


In [0]:
a[1, 1:].shape

(2,)

In [0]:
a[1:2, 1:].shape

(1, 2)

# 코드 14-1 : 선형 연립 방정식 풀이
## numpy_linear_ex.py

In [0]:
import numpy as np

a = np.array([[2, 3], [1, -2]])
b = np.array([1, 4])
x = np.linalg.solve(a, b)

print(x)

In [0]:
b = np.array([4, 5, 6])
b

## 대화창 실습 : 행렬식

In [0]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

In [0]:
b = np.array([[1, 2], [3, -6]])
np.linalg.det(b)

In [0]:
b = np.array([[1, 2], [1, 2]])
np.linalg.det(b)

# 이 밑으로는 책 순서와 무관한 코드

In [0]:
c = a + b
c

In [0]:
c.shape

In [0]:
c.ndim

In [0]:
c.size

In [0]:
c.itemsize

In [0]:
d = np.array([2,4,6,8,10])
d.size

In [0]:
d.itemsize

In [0]:
a = np.array([1, 2, 3], dtype='int32')
b = np.array([4, 5, 6], dtype='int64')
print(a.dtype)
print(b.dtype)

In [0]:
c = a + b
print(c.dtype)

## 2차원 ndarray의 연산

In [0]:
a = np.array([[1, 2], [3, 4]])

In [0]:
b = np.array([[10, 20], [30, 40]])

In [0]:
a + b

In [0]:
a - b

In [0]:
a * b

In [0]:
a / b

In [0]:
np.matmul(a, b)

In [0]:
g = a @ b
print(g)

In [0]:
a[0, 0] * b[0, 0] + a[0, 1] * b[1, 0]

In [0]:
a = np.array([[1, 2], [3, 4]])
a + 1

In [0]:
a * 2

## numpy 배열 생성

In [0]:
import numpy as np

a = np.zeros((2, 3))
print('a =', a)
b = np.ones((2, 3))
print('b =', b)
c = np.full((2, 3), 100)
print('c =', c)
d = np.eye(3)
print('d =', d)
e = np.random.random((3, 4))
print('e =', e)

## arange() 실습

In [0]:
np.arange(0, 10)

In [0]:
np.arange(0, 10, 2)

In [0]:
np.arange(0, 10, 3)

In [0]:
np.arange(0.0, 1.0, 0.2)

In [0]:
a = np.array([[1, 2], [3, 4]])
a + 1

In [0]:
a - 1

In [0]:
a * 100

In [0]:
a / 100

In [0]:
a ** 2

In [0]:
a ** 10

## 배열의 생성과 초기화

In [0]:
np.zeros((2, 3))

In [0]:
np.ones((2, 3))

In [0]:
np.full((2, 3), 100)

In [0]:
np.eye(3)

In [0]:
np.random.random((2, 3))

## arange 실습

In [0]:
np.arange(0, 10)

In [0]:
np.arange(0, 10, 2)

In [0]:
np.arange(0, 10, 3)

In [0]:
np.arange(0.0, 1.0, 0.2)

In [0]:
np.linspace(0, 10, 5)

In [0]:
np.linspace(0, 10, 4)

## reshape 실습

In [0]:
np.arange(0,10).reshape(2,5)

In [0]:
np.arange(0,10).reshape(5,2)

In [0]:
np.arange(0,10).reshape(3,3)

In [0]:
np.arange(0, 24).reshape(4, 3, 2)

In [0]:
print(a[np.array([0, 1])])